# Generated by Django 5.2.13 on 2026-06-12 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_alter_calllog_notes'),
        ('staff', '0011_staffdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadcapture',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staff'),
        ),
    ]
