# Generated by Django 5.2.13 on 2026-06-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_alter_staff_first_name_alter_staff_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dept_name',
            field=models.CharField(choices=[('Technical', 'Technical'), ('Management', 'Management'), ('Sales', 'Sales Department'), ('Marketing', 'Marketing')], max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='staffrole',
            name='role_name',
            field=models.CharField(choices=[('Developer', 'Developer'), ('Trainer', 'Trainer'), ('Admin', 'Admin'), ('Manager', 'Manager'), ('HR', 'HR'), ('BDE', 'BDE'), ('Telecall', 'Telecall'), ('Sales Exec', 'Sales Exec'), ('Digital Marketing', 'Digital Marketing'), ('Content Creator', 'Content Creator')], max_length=100, unique=True),
        ),
    ]
