# Generated by Django 5.2.13 on 2026-06-11 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_alter_department_dept_name_alter_staffrole_role_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='staff/documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_documents', to='staff.staff')),
            ],
            options={
                'db_table': 'staff_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
