# Generated by Django 5.2.13 on 2026-06-15 05:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_staffdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='monthly_target',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
